name: Application CI

on:
  push:
  pull_request:
      
jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"
          
      - name: Setup Flutter SDK
        if: steps.check_files.outputs.files_exists == 'true'
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: '3.10.6'

      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter packages get

      - name: Setup Dart Code Metrics
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub get dart_code_metrics

      - name: Dart Code Metrics
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          dirs_to_analyse=""
          if [ -d lib ]; then dirs_to_analyse+=" lib"; fi
          if [ -d test ]; then dirs_to_analyse+=" test"; fi
          if [ -d example ]; then dirs_to_analyse+=" example"; fi
          if [ dirs_to_analyse != "" ]
          then
            dart run dart_code_metrics:metrics \
              analyze \
              $dirs_to_analyse \
              --fatal-warnings \
              --fatal-performance \
              --fatal-style
            dart run dart_code_metrics:metrics \
              check-unused-files \
              $dirs_to_analyse \
              --fatal-unused
            dart run dart_code_metrics:metrics \
              check-unused-code \ 
              $dirs_to_analyse \
              --fatal-unused
          fi

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter test --machine
