name: Application ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"

      - name: Setup Flutter SDK
        if: steps.check_files.outputs.files_exists == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.6"
          channel: 'stable'
          
          
      
      - name: Check flutter sdk version
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter --version
      
      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter pub get
      
      - name: Setup Solid Lint
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub add --dev solid

      - name: Solid Lint
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          dirs_to_analyse=""
          if [ -d lib ]; then dirs_to_analyse+=" lib"; fi
          if [ -d test ]; then dirs_to_analyse+=" test"; fi
        
          if [ dirs_to_analyse != "" ]
          then
            flutter analyze $dirs_to_analyse
          fi

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
