name: Application CI

on:
  push:
  pull_request:
      
jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"

      - name: Setup Dart SDK
        if: steps.check_files.outputs.files_exists == 'true'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.0.6" 

      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub get

      - name: Setup Solid Lint
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub add --dev solid

      - name: Solid Lint
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          dirs_to_analyse=""
          if [ -d lib ]; then dirs_to_analyse+=" lib"; fi
          if [ -d test ]; then dirs_to_analyse+=" test"; fi

          if [ "$dirs_to_analyse" != "" ]
          then
            dart analyze $dirs_to_analyse
          fi

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart test --machine
