name: Application CI

on:
  push:
  pull_request:
      
jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"
          
      - name: Setup Flutter SDK
        if: steps.check_files.outputs.files_exists == 'true'
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: '3.10.6'

      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter packages get

      - name: Run Solid Lints
        run: dart analyze --fatal-warnings

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter test --machine
